### ISSUE TITLE
AdvancedConfig is not defined

### ISSUE THREAD

**Issue by sysRoot** [blizzhackers/kolbot-SoloPlay#21]
![image](https://user-images.githubusercontent.com/414285/174389779-6c81be76-9402-499b-94e0-14d1906b4ffc.png)
I get this error and am not understanding. Am I supposed to apply an advanced config, where and how? I

**Comment by theBGuy** [comment]
I think either your soloplay download is out of date or you kolbot one is

**Comment by sysRoot** [comment]
Will give it a try, I am using BlizzHackers and The SoloPlay was downloaded just now from the referenced repository on main page, will report back after a fresh git clone of kolbot.

**Comment by sysRoot** [comment]
A fresh clone did work, my copy of kolbot was a few weeks old. 
Thank you and sorry for the issue opened.
