### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by magace** [blizzhackers/kolbot-SoloPlay#34]
Love it running 50+ with minimal issues.
Issue 1
Endless Crafting Loop.  I noticed sometimes they get stuck removing and adding stuff to cube and I have to manually remove it from cube for it to correct it's self.
![image](https://user-images.githubusercontent.com/7795098/182660803-bff98591-27ca-45e3-8ea1-156b8bc192cf.png)

Issue 2
Automule bug?
I noticed all my paladins filling up with keys and not muling excess ones.  I removed them from pickit and it still didn't sell them.   Automule would trigger pala joins but never drops items so it would go into a endless loop.

Thanks again!

**Comment by aim2kill** [comment]
look like u download a different branch for solo or kolbot

**Comment by theBGuy** [comment]
That's a good point, which branch of kolbot are you using and which branch of soloplay are you using?

**Comment by magace** [comment]
I updated from the BH master kolbot and main solo play.  I will update again and make sure I got the updates 29 days ago like 99% sure I did though.

**Comment by theBGuy** [comment]
That's fine then, just wanted to check if you mixed and matched the current development branches of kolbot and soloplay. At the moment I would recommend using the kolbot/AttackCleanup branch along with the soloplay/MagicNums branch. Then let me know if you still see this issue

**Comment by magace** [comment]
I just un commented kolton pickit from solo play pala/sorc config and noticed a couple paladins filling up with keys and never muling them.  Not using torch system.   They would get into a endless loop of joining mule games.  I will try those branches out.  

On a side note when running so many chars with 1 mule acct they would get a bit confused when multiple trigger at the same time.  I would think it should check if the mule is free before exiting the game.  It can be a little harsh on cdkeys when like 5 trigger and only 1 gets muled the rest just make a new game and get triggered again.  This is more of a Kol thing not soloplay just throwing it out there.

**Comment by aim2kill** [comment]
the mule always in game? unless is get full. either increase the time u other toon way for the mules to get back in the game or split the profiles and make 2 mules

**Comment by magace** [comment]
Updated to magic numbers and the crafting issue still seems to be happening.
[screen-capture.webm](https://user-images.githubusercontent.com/7795098/183063561-ccec68ce-8b11-4d4d-ae42-5cc61395bdeb.webm)

**Comment by aim2kill** [comment]
I noticed that the jewel never get inside the cube, right?

**Comment by theBGuy** [comment]
I have not been able to replicate your crafting loop issue, is it still happening?

**Comment by theBGuy** [comment]
Haven't been able to replicate
