### ISSUE TITLE
2nd Bot always loads in full screen

### ISSUE THREAD

**Issue by PunchLOD** [blizzhackers/kolbot-SoloPlay#36]
My first bot will load up in window and work perfectly. When I create a 2nd bot profile and try to run another bot it loads in full screen and causes it to crash. 

I've tried cloning the first bot's profile, thinking I may have done something wrong. Parameters are set to -w -sleepy -ftj. Still same result.

Anyone else have this issue?

**Comment by theBGuy** [comment]
This isn't a soloplay related issue. You might be be off taking this over to the blizzhackers/kolbot repo. I've never heard of anyone else having this issue.
