### ISSUE TITLE
type.toLowerCase is not a function error

### ISSUE THREAD

**Issue by ly19811105** [blizzhackers/kolbot-SoloPlay#37]
always got this error ,type.toLowerCase is not a function

this function is under TownOverrides.js, 

/*new Overrides.Override(Town, Town.drinkPots, function(orignal, type) {
	let objDrank = orignal(type, false);
	
	if (objDrank.potName) {
		let objID = objDrank.potName.split(" ")[0].toLowerCase();
        console.log("ÿc8Kolbot-SoloPlayÿc0: buying " + objID + " " + type + " check");
		if (objID) {
			// non-english version
			if (!CharData.buffData[objID]) {
				**objID = type.toLowerCase();**
			}

			if (!CharData.buffData[objID].active() || CharData.buffData[objID].timeLeft() <= 0) {
				CharData.buffData[objID].tick = getTickCount();
				CharData.buffData[objID].duration = objDrank.quantity * 30 * 1000;
			} else {
				CharData.buffData[objID].duration += (objDrank.quantity * 30 * 1000) - (getTickCount() - CharData.buffData[objID].tick);
			}

			console.log("ÿc9DrinkPotsÿc0 :: drank " + objDrank.quantity + " " + objDrank.potName + "s. Timer [" + Developer.formatTime(CharData.buffData[objID].duration) + "]");
		}
	}

	return true;
}).apply();
*/

please help check and advise .thanks.

**Comment by theBGuy** [comment]
Are you using a non-english download of diablo?
