### ISSUE TITLE
Script bug when running the Summoner

### ISSUE THREAD

**Issue by ImInAdream** [blizzhackers/kolbot-SoloPlay#40]
Hi,

I noticed that sometimes solo bots might get stuck in a2 summoner quest. It does not depend really on the class.
I was running 8 bots for testing in single player, and 3 of them got stuck in the following loop:

- the script starts running, 
- they tp at the sanctuary,
-  then they idle for a few seconds, 
- then they switch to the Tombs script, 
- they go back to town and quit the game since they cannot access tombs.

Best regards,

**Comment by theBGuy** [comment]
I need to create a bug report template. Alright,

1) What branch of kolbot are you running? When was it downloaded?
2) What branch of SoloPlay are you running? When was it downloaded?
3) What do the logs say? Can you provide them? If so, use pastebin, do not copy and paste the entire log here.
