### ISSUE TITLE
Errors while item Handlick

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot-SoloPlay#44]
Geting errors with items on cursor.

file:functions/temoverrides.js:580 reference to undefined property sdk.clicktypes.click.mercenary

also when stash handling

file:functions/temoverrides.js:330 reference to undefined property sdk.clicktypes.click.left

**Comment by theBGuy** [comment]
Update kolbot, always check that first.

**Comment by theBGuy** [comment]
That would be my bad, I assumed you were using the dev branch not the main one

**Comment by tyson-dev** [comment]
Totally fine M8, ty for helping.

I'm checking with dev branch, looks fine now.
