### ISSUE TITLE
hdin attack issue

### ISSUE THREAD

**Issue by saleen275** [blizzhackers/kolbot-SoloPlay#47]
im making a hammerdin and ive noticed it dont look like hes even attacking??? it looks like he just stands and teles to monsters and lets the merc kill them...but ive have noticed a few times when the merc have died he does kill the monsters..why cant i see his hammers attacking tho?

**Comment by aim2kill** [comment]
Packets ca5ting

**Comment by saleen275** [comment]
ohh ok..thx
