### ISSUE TITLE
Min Gametime

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot-SoloPlay#48]
Where can i lower/disable min gametime?
I switch keys on every chicken/restart so that's not needed here.

**Comment by theBGuy** [comment]
Switching keys doesn't do anything, ip address is tracked.

**Comment by tyson-dev** [comment]
yes it does, it does e.g nullify the effect that my rushers get silenced after 3rd run without key switching ( i have edited rusher script with detailed instructions for human rushees).

Ofc one may have to keep the 20games/ip/hour additionally which is what you probably mean.

I am pretty sure you can get around min game time r/ds with key switching as my classic sorc was out of money and so leaving and reopening games between 1 and 3 minutes without problems.

Please info where to change min gametime in SoloPlay M8.

Ty so much

**Comment by theBGuy** [comment]
Same way as normal kolbot, inside the entry script

**Comment by tyson-dev** [comment]
i am dumb, ty :D
