### ISSUE TITLE
not using meteor on CI in NM

### ISSUE THREAD

**Issue by tyson-dev** [blizzhackers/kolbot-SoloPlay#50]
lvl 50 sorc / stepping / NM / Meteorb build

not using her lvl3 meteor on CI de seis in NM.

**Comment by aim2kill** [comment]
Stepping dont use meteor at all, so not idea why u have 3 points on meteor

**Comment by tyson-dev** [comment]
If you don't have a clue it's worth checking the scripts i guess. I haven't manually skilled. I just saw her skipping ci ( and only ci ) de seis and paused to use her meteor lvl 3 on de seis which was pretty effecitve. She had skilled all herself so why not use meteor on CI?

**Comment by theBGuy** [comment]
The meteor skill most likely came from an item. The way I have attack skill selection set up it uses known values instead of generating skill info for every single available skill. It was taking too long and led to ineffective choices

**Comment by tyson-dev** [comment]
> The meteor skill most likely came from an item. The way I have attack skill selection set up it uses known values instead of generating skill info for every single available skill. It was taking too long and led to ineffective choices

Yeah that's it, comes from an item, sry guys. Understandable she is not using item skills. Meteor Looks like a 1 point wonder to me against CI though.

**Comment by tyson-dev** [comment]
got ya, she also is leveling cows now so probably skipping de seis once or twice in NM should be fine. Shouldn't be too many other CI in NM anyway.

**Comment by aim2kill** [comment]
As soon as she swap to lvling build she will be able to kill him
