### ISSUE TITLE
type.toLowerCase is not a function

### ISSUE THREAD

**Issue by mathgonzlez** [blizzhackers/kolbot-SoloPlay#53]
i Receive the next error, and my char cant complete den and Andy (townoverrides.js #29) type.toLowerCase is not a function (Area: Rogue Encampment, Ping:0, Game: ), i test pala, sorc, barb and necro and all the same.

versions:

latest kolbot
latest soloplay
d2 lod en-US 1.14d

![error](https://user-images.githubusercontent.com/57609433/208256855-229c75de-5742-4b9c-9aa4-6e2d8d2fab75.jpeg)

**Comment by aim2kill** [comment]
I think u using non english  version

**Comment by mathgonzlez** [comment]
My game is completely in english, i attached a screen from my installers.

![language](https://user-images.githubusercontent.com/57609433/208261083-3e61f4f5-93d2-40a1-b1aa-e8ea2c80e462.JPG)


![installer](https://user-images.githubusercontent.com/57609433/208261503-28ecc41e-9ca1-4e9b-908a-c255f36926f0.JPG)

Thanks!!

**Comment by theBGuy** [comment]
Can you test a new character with #54 to see if the issue still pops up?

**Comment by mathgonzlez** [comment]
> Can you test a new character with #54 to see if the issue still pops up?

Now den and andy is working fine, but in ACT 2 the cube and amulet is done but the staff failed.
