### ISSUE TITLE
SoloPlay creates it's own game name and pw and not what is listed in bot.

### ISSUE THREAD

**Issue by twiztiddreamz** [blizzhackers/kolbot-SoloPlay#63]
I've looked everywhere to try and figure out the issue.  When I set up kolbot and soloplay, with a Game Name and password, it never uses it.  It constantly creates it's own game name and pw.  If I select D2BotLead.dbj it will actually create the game name and password as I specified.   I just downloaded kolbot and kolbot solo play today, so it's a fresh install.   Any help would be appreciated.

**Comment by Mercoory** [comment]
It is not an issue. This is how kolbot-SoloPlay works - as its name intended - meant to play solo without anybody joining their game. 
The script creates its own game name and pass ( check OOGOverrides.js line 136 ).

If you want to change this behavior, than change the gameinfo.gameName  and gameInfo.gamePass in the D2BotSoloPlay.dbj according your needs.

But as it is written in the Readme of the repo: **SoloPlay works by set it and forget philosophy**.

**Comment by theBGuy** [comment]
@ Mercoory is correct, closing this out.
