### ISSUE TITLE
ISSUE TO GO TO FINAL BUILD FOR SUMMON NECRO

### ISSUE THREAD

**Issue by Soufin198** [blizzhackers/kolbot-SoloPlay#67]
Hello guys, 

My necro doesn't go to final build and he's still to levelingbuild though he's level 53. 

Can u tell me which line i have to modify to permit him to switch the current build from levelingbuild to summonbuild ?

Thank you in advance for your answer

**Comment by theBGuy** [comment]
Your issue is you didn't read the readme
