### ISSUE TITLE
trying to initialize the bot but error appears

### ISSUE THREAD

**Issue by Gryphon309** [blizzhackers/kolbot-SoloPlay#70]
![erro](https://github.com/blizzhackers/kolbot-SoloPlay/assets/158472066/6e4fcf44-e6b5-4fe5-9cde-f4c38c1d8db8)

When downloading the files, I notice that two files are missing from the YouTube video folder that demonstrates the installation.
These are the D2 Botsolocleaner.dbj and default.dbj files.
Could they be causing this image error?

**Comment by theBGuy** [comment]
My YouTube video is outdated. The problem here is you need to use the restructure branch not the main branch. I'm assuming you downloaded via svn so check the branches folder for it

**Comment by Gryphon309** [comment]
I downloaded it via get hub desktop and zip, but none of them worked using restructuring, I moved d2botsoloplay.dbj to the folder mentioned in the video and replaced the libs folder, but it still didn't work.
I don't know what I'm doing wrong.

**Comment by theBGuy** [comment]
New setup video https://youtu.be/SWBbVQTmk_A?si=cPVCVXz05DxMU4Wn

**Comment by Gryphon309** [comment]
Thanks for the help, it's working perfectly.
