### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rbenn08** [blizzhackers/kolbot-SoloPlay#71]

**Comment by rbenn08** [comment]
![image_2024-02-24_154240436](https://github.com/blizzhackers/kolbot-SoloPlay/assets/161164892/1d6fa0b9-c406-4a82-8104-bc5f8b831cdb)
![image_2024-02-24_154253287](https://github.com/blizzhackers/kolbot-SoloPlay/assets/161164892/44470c5b-a42b-48c7-a381-30ae0645db75)

**Comment by theBGuy** [comment]
Are you unable to read? SoloLeveling is not Soloplay, this repo isn't even where you downloaded that from

**Comment by theBGuy** [comment]
You literally have the SoloLeveling repo open in your first screenshot. How did you even end up here

**Comment by rbenn08** [comment]
> You literally have the SoloLeveling repo open in your first screenshot. How did you even end up here

Said " I'm new here" Do you mean this is the wrong page on github? I only know basic coding.. not much about github.
