### ISSUE TITLE
Cant Run At All (Solowant.js)

### ISSUE THREAD

**Issue by Trebla99** [blizzhackers/kolbot-SoloPlay#73]
Here Are The Copy-Paste Error Given By The Bots

[Error(155)] File(Kolbot\libs\soloplay\functions\solowant.js:8) TypeError: redeclaration of const SoloWants
[Error (0)] File(Kolbot\libs\soloplay\functions\global.js:214) Error : Failed to include SoloPlay/functions/SoloWants.js

**Comment by theBGuy** [comment]
Did you mix and match an old version with this one?

**Comment by Trebla99** [comment]
Seem Like It
Have Done A Clean Install And Its Working
