### ISSUE TITLE
Build not being selected

### ISSUE THREAD

**Issue by Django98782** [blizzhackers/kolbot-SoloPlay#78]
Hi,
thank you so much for the bot!

for the soloplay, under the infotag, i typed “Whirlwind” but my barb is already lvl 70 and has 0 whirlwind skill selected..

also same thing for my sorceress.. i typed “Lightning” but uses blizz and meteor most of the time and has no lightning skills selected except for static and other support skills.

please help

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/kolbot-SoloPlay#q-why-isnt-the-bot-making-the-build-i-selected
